### ISSUE TITLE
The detected CUDA version (12.2) mismatches the version that was used to compile PyTorch (11.3). Please make sure to use the same CUDA versions.

### ISSUE THREAD

**Issue by FUIGUIMURONG** [sijieaaa/pointnet2_torch_cuda11#2]
Thanks for releasing code. When I install pointnet, I met the problem as the title shows. My environment is 
pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0
 Can you help me with that.

**Comment by sijieaaa** [comment]
Can you show (snapshot) me the results of the following several commands?

1.

```
python
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```

2.

```
nvcc --version
```

**Comment by FUIGUIMURONG** [comment]
Thanks for replying, I create the virtual environment.
1. .
>>> import torch
>>> print(torch.__version__)
1.12.0
>>> print(torch.cuda.is_available())
True
>>>
KeyboardInterrupt
2.(SQA_3D) sdp@xdy-Super-Server:~/SQA3D-master/Pointnet2.ScanNet/pointnet2$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0

It is so weird that the nvcc --versioin output cuda12.2, as I donnot install cuda 12.2

**Comment by sijieaaa** [comment]
Your CUDA version is too high (12.2), which is incompatible with your torch.
Note that the true CUDA version refers to nvcc version, not nvidia-smi version. They are two different things.
So, there are several possible options:

1. reinstall another CUDA 11 version, and reinstall torch that is compatible with it.
[https://developer.nvidia.com/cuda-11.3.0-download-archive](url)
[https://developer.nvidia.com/cuda-11-8-0-download-archive](url)
```
conda create -n testpointnet2 python=3.8
conda activate testpointnet2
pip3 install torch torchvision torchaudio
git clone https://github.com/sijieaaa/pointnet2_torch_cuda11.git
cd pointnet2_torch_cuda11
python setup.py install
```


3. reinstall torch (preview version) that supports CUDA 12
```
conda create -n testpointnet2 python=3.8
conda activate testpointnet2
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
git clone https://github.com/sijieaaa/pointnet2_torch_cuda11.git
cd pointnet2_torch_cuda11
python setup.py install
```

4. just reinstall torch (stable version)
```
conda create -n testpointnet2 python=3.8
conda activate testpointnet2
pip3 install torch torchvision torchaudio
git clone https://github.com/sijieaaa/pointnet2_torch_cuda11.git
cd pointnet2_torch_cuda11
python setup.py install
```

**Comment by FUIGUIMURONG** [comment]
1.Thanks for answering, you are so kind. I do some operations as you instruct and the nvcc --version is showing like:
(SQA_3D) sdp@xdy-Super-Server:~/SQA3D-master/pointnet2_torch_cuda11-main$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

2.It seems Cuda version is all right, but I met another question:
(SQA_3D) sdp@xdy-Super-Server:~/SQA3D-master/pointnet2_torch_cuda11-main$ python setup.py install
running install
/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pointnet2.egg-info/PKG-INFO
writing dependency_links to pointnet2.egg-info/dependency_links.txt
writing top-level names to pointnet2.egg-info/top_level.txt
reading manifest file 'pointnet2.egg-info/SOURCES.txt'
writing manifest file 'pointnet2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'pointnet2._ext' extension
creating build
creating build/temp.linux-x86_64-cpython-39
creating build/temp.linux-x86_64-cpython-39/_ext_src
creating build/temp.linux-x86_64-cpython-39/_ext_src/src
gcc -pthread -B /home/sdp/miniconda3/envs/SQA_3D/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/sdp/miniconda3/envs/SQA_3D/include -fPIC -O2 -isystem /home/sdp/miniconda3/envs/SQA_3D/include -fPIC -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/TH -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/THC -I/home/sdp/miniconda3/envs/SQA_3D/include -I/home/sdp/miniconda3/envs/SQA_3D/include/python3.9 -c _ext_src/src/ball_query.cpp -o build/temp.linux-x86_64-cpython-39/_ext_src/src/ball_query.o -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
In file included from _ext_src/include/utils.h:7,
                 from _ext_src/src/ball_query.cpp:7:
/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录
    5 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by FUIGUIMURONG** [comment]
> 1.Thanks for answering, you are so kind. I do some operations as you instruct and the nvcc --version is showing like: (SQA_3D) sdp@xdy-Super-Server:~/SQA3D-master/pointnet2_torch_cuda11-main$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Sun_Mar_21_19:15:46_PDT_2021 Cuda compilation tools, release 11.3, V11.3.58 Build cuda_11.3.r11.3/compiler.29745058_0
> 
> 2.It seems Cuda version is all right, but I met another question: (SQA_3D) sdp@xdy-Super-Server:~/SQA3D-master/pointnet2_torch_cuda11-main$ python setup.py install running install /home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated. !!
> 
> ```
>     ********************************************************************************
>     Please avoid running ``setup.py`` directly.
>     Instead, use pypa/build, pypa/installer or other
>     standards-based tools.
> 
>     See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
>     ********************************************************************************
> ```
> 
> !! self.initialize_options() /home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated. !!
> 
> ```
>     ********************************************************************************
>     Please avoid running ``setup.py`` and ``easy_install``.
>     Instead, use pypa/build, pypa/installer or other
>     standards-based tools.
> 
>     See https://github.com/pypa/setuptools/issues/917 for details.
>     ********************************************************************************
> ```
> 
> !! self.initialize_options() running bdist_egg running egg_info writing pointnet2.egg-info/PKG-INFO writing dependency_links to pointnet2.egg-info/dependency_links.txt writing top-level names to pointnet2.egg-info/top_level.txt reading manifest file 'pointnet2.egg-info/SOURCES.txt' writing manifest file 'pointnet2.egg-info/SOURCES.txt' installing library code to build/bdist.linux-x86_64/egg running install_lib running build_ext building 'pointnet2._ext' extension creating build creating build/temp.linux-x86_64-cpython-39 creating build/temp.linux-x86_64-cpython-39/_ext_src creating build/temp.linux-x86_64-cpython-39/_ext_src/src gcc -pthread -B /home/sdp/miniconda3/envs/SQA_3D/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/sdp/miniconda3/envs/SQA_3D/include -fPIC -O2 -isystem /home/sdp/miniconda3/envs/SQA_3D/include -fPIC -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/TH -I/home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/THC -I/home/sdp/miniconda3/envs/SQA_3D/include -I/home/sdp/miniconda3/envs/SQA_3D/include/python3.9 -c _ext_src/src/ball_query.cpp -o build/temp.linux-x86_64-cpython-39/_ext_src/src/ball_query.o -O2 -I_ext_src/include -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1013" -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14 In file included from _ext_src/include/utils.h:7, from _ext_src/src/ball_query.cpp:7: /home/sdp/miniconda3/envs/SQA_3D/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: 没有那个文件或目录 5 | #include <cuda_runtime_api.h> | ^~~~~~~~~~~~~~~~~~~~ compilation terminated. error: command '/usr/bin/gcc' failed with exit code 1

I have solved the problem by "conda install cudatoolkit-dev==11.3.1 -c conda-forge". The lack of "cuda_runtime_api.h" may arise from my initial installing the castration version of cudatoolkit. Anyway, thanks for following my question.

**Comment by OrangeJuice3211** [comment]
> Can you show (snapshot) me the results of the following several commands?
> 
> 
> ```
> python
> import torch
> print(torch.__version__)
> print(torch.cuda.is_available())
> ```
> 
> 
> ```
> nvcc --version
> ```

Hello，my error is the same as the title, the output of the above command are:
`>python
Python 3.8.18 (default, Sep 11 2023, 13:40:15)
>import torch
print(torch.__version__)
1.10.0+cu113
>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0`
So, it seems that cuda12.3 is in my host (not in the anaconda virtual environment), but there is cuda11.3 in my venv! it's the version that match the pytorch 1.10.0（in my virtual environment).
The system calls the CUDA in the host, not the CUDA in the virtual environment, it stands to reason that it shouldn't, and the cuda in the virtual environment should be called when running code in the virtual environment, can anyone help me?

**Comment by OrangeJuice3211** [comment]
> Can you show (snapshot) me the results of the following several commands?
> 
> 
> ```
> python
> import torch
> print(torch.__version__)
> print(torch.cuda.is_available())
> ```
> 
> 
> ```
> nvcc --version
> ```
Hello，my error is the same as the title, the output of the above command are:
`>python
Python 3.8.18 (default, Sep 11 2023, 13:40:15)
>import torch
print(torch.__version__)
1.10.0+cu113
>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0`
So, it seems that cuda12.3 is in my host (not in the anaconda virtual environment), but there is cuda11.3 in my venv! it's the version that match the pytorch 1.10.0（in my virtual environment).
The system calls the CUDA in the host, not the CUDA in the virtual environment, it stands to reason that it shouldn't, and the cuda in the virtual environment should be called when running code in the virtual environment, can anyone help me?

**Comment by OrangeJuice3211** [comment]
> Can you show (snapshot) me the results of the following several commands?
> 
> 
> ```
> python
> import torch
> print(torch.__version__)
> print(torch.cuda.is_available())
> ```
> 
> 
> ```
> nvcc --version
> ```

Hello，my error is the same as the title, the output of the above command are:
`python
Python 3.8.18 (default, Sep 11 2023, 13:40:15)
import torch
print(torch.__version__)
1.10.0+cu113
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0`
So, it seems that cuda12.3 is in my host (not in the anaconda virtual environment), but there is cuda11.3 in my venv! it's the version that match the pytorch 1.10.0（in my virtual environment).
The system calls the CUDA in the host, not the CUDA in the virtual environment, it stands to reason that it shouldn't, and the cuda in the virtual environment should be called when running code in the virtual environment, can anyone help me?

**Comment by OrangeJuice3211** [comment]
> Can you show (snapshot) me the results of the following several commands?
> 
> 
> ```
> python
> import torch
> print(torch.__version__)
> print(torch.cuda.is_available())
> ```
> 
> 
> ```
> nvcc --version
> ```

Hello，my error is the same as the title, the output of the above command are:

python 
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
import torch print(torch.__version__) 1.10.0+cu113 
nvcc --version 
nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Wed_Nov_22_10:17:15_PST_2023 Cuda compilation tools, release 12.3, V12.3.107 Build cuda_12.3.r12.3/compiler.33567101_0

So, it seems that cuda12.3 is in my host (not in the anaconda virtual environment), but there is cuda11.3 in my venv! it's the version that match the pytorch 1.10.0（in my virtual environment).
The system calls the CUDA in the host, not the CUDA in the virtual environment, it stands to reason that it shouldn't, and the cuda in the virtual environment should be called when running code in the virtual environment, can anyone help me?

**Comment by OrangeJuice3211** [comment]
> > Can you show (snapshot) me the results of the following several commands?
> > ```
> > python
> > import torch
> > print(torch.__version__)
> > print(torch.cuda.is_available())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > nvcc --version
> > ```
> 
> Hello，my error is the same as the title, the output of the above command are:
> 
> python Python 3.8.18 (default, Sep 11 2023, 13:40:15) import torch print(torch.**version**) 1.10.0+cu113 nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Wed_Nov_22_10:17:15_PST_2023 Cuda compilation tools, release 12.3, V12.3.107 Build cuda_12.3.r12.3/compiler.33567101_0
> 
> So, it seems that cuda12.3 is in my host (not in the anaconda virtual environment), but there is cuda11.3 in my venv! it's the version that match the pytorch 1.10.0（in my virtual environment). The system calls the CUDA in the host, not the CUDA in the virtual environment, it stands to reason that it shouldn't, and the cuda in the virtual environment should be called when running code in the virtual environment, can anyone help me?

How do I do if I want the program to call CUDA in a virtual environment instead of CUDA in the host?
